
## xeCompile starts at 11/01/2024 12:24:29 simonett V23.03.131.s001, HOST: sjcvl-simonett, PID: 8644, DISPLAY: none
xeCompile compilePPC.qel
## 64bit program from /lan/cva_rel/23h1_wxe/23.03.131.s001/tools.lnx86/bin on Linux 3.10.0-1160.2.2.el7.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libhdl.so - 23H1_WXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_WXE, V23.03.131.s001            
#)libimp.so - 23H1_WXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_WXE, V23.03.131.s001            
#)libudq.so - 23H1_WXE, V23.03.131.s001            
#)libudqr.so - 23H1_WXE, V23.03.131.s001            
#)liboptutil.so - 23H1_WXE, V23.03.131.s001            
#)libpich.so - 23H1_WXE, V23.03.131.s001            
#)libtich.so - 23H1_WXE, V23.03.131.s001            
#)libdb.so - 23H1_WXE, V23.03.131.s001            
#)libsmDB.so - 23H1_WXE, V23.03.131.s001            
#)libtypedb.so - 23H1_WXE, V23.03.131.s001            
#)libudqr.so - 23H1_WXE, V23.03.131.s001            
#)libhdldb.so - 23H1_WXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_WXE, V23.03.131.s001            
#)libcmp.so - 23H1_WXE, V23.03.131.s001            
#)libddb.so - 23H1_WXE, V23.03.131.s001            
#)libudp.so - 23H1_WXE, V23.03.131.s001            
#)libPDBCommands.so - 23H1_WXE, V23.03.131.s001            
#)libhwConfig.so - 23H1_WXE, V23.03.131.s001            
#)libCompilerRT.so - 23H1_WXE, V23.03.131.s001            
#)libclkBDD.so - 23H1_WXE, V23.03.131.s001            
#)libsdltm.so - 23H1_WXE, V23.03.131.s001            
#)libet3compile.so - 23H1_WXE, V23.03.131.s001            
#)libdb2util.so - 23H1_WXE, V23.03.131.s001            
#)liboptutil.so - 23H1_WXE, V23.03.131.s001            
#)libdb3.so - 23H1_WXE, V23.03.131.s001            
#)libet3wrapper.so - 23H1_WXE, V23.03.131.s001            
#)libsideFile.so - 23H1_WXE, V23.03.131.s001            
#)libdbgPrepare.so - 23H1_WXE, V23.03.131.s001            
#)libucdbwrt.so - 23H1_WXE, V23.03.131.s001            
#)libucdb_sh.so - 23H1_WXE, V23.03.131.s001            
#)libradb.so - 23H1_WXE, V23.03.131.s001            
#)libeclutil.so - 23H1_WXE, V23.03.131.s001            
#)libqtutil.so - 23H1_WXE, V23.03.131.s001            
#)libdbgutil.so - 23H1_WXE, V23.03.131.s001            
#)libuxeenglic.so - 23H1_WXE, V23.03.131.s001            
#)libjsoncpp.so - 23H1_WXE, V23.03.131.s001            
#)libgenlics.a - 23H1_WXE, V23.03.131.s001            
#)libtcl.so - 23H1_WXE, V23.03.131.s001            
#)libtk.so - 23H1_WXE, V23.03.131.s001            
#)libtkdnd.so - 23H1_WXE, V23.03.131.s001            
#)libtix.so - 23H1_WXE, V23.03.131.s001            
#)libqt.so - 23H1_WXE, V23.03.131.s001            
#)libqtutil.so - 23H1_WXE, V23.03.131.s001            
#)libsd.so - 23H1_WXE, V23.03.131.s001            
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63416
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63416
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 4
  Name: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
  Vendor: GenuineIntel, family: 6, model: 85, stepping: 4
  CPU MHz: 2294.609, BogoMIPS: 4589.21, virtualization: full
  L1d cache: 32K, L1i cache: 32K, L2 cache: 1024K, L3 cache: 25344K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):       15       11        4        0        0        8
Swap (GB):        7        1        6
* Load info:
  782 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
               2.78 ( 70% CPU) |   1.58 ( 39% CPU) |   1.16 ( 29% CPU)
System info: sjcvl-simonett - xeCompile - 8644 8642 - qtInit - 2024-11-01 12:24:29 - 2.78 70% 1.58 39% 1.16 29% - 15 11 4 8 7 1 6
000,000 s: XEC> design
000,000 s: INFO 53652: checking Palladium_Z2_Compiler (23.00) ...

## oomr starts at 11/01/2024 12:24:30 simonett V23.03.131.s001, HOST: sjcvl-simonett, PID: 8834, DISPLAY: none
oomr hdldb xcva_top
## 64bit program from /lan/cva_rel/23h1_wxe/23.03.131.s001/tools.lnx86/bin on Linux 3.10.0-1160.2.2.el7.x86_64 64bit
(c) 1991-2021 Cadence Design Systems, Inc. All rights reserved worldwide.
See files in <rootdir>/share/vxe/install/Copyrights
#)libimport.so - 23H1_WXE, V23.03.131.s001            
#)libmcp.so - 23H1_WXE, V23.03.131.s001            
#)libdataStruct.so - 23H1_WXE, V23.03.131.s001            
#)libdb.so - 23H1_WXE, V23.03.131.s001            
#)libsmDB.so - 23H1_WXE, V23.03.131.s001            
000,000 s: oomr - 23H1_WXE, V23.03.131.s001            
#)libtypedb.so - 23H1_WXE, V23.03.131.s001            
000,000 s: 
#)libudqr.so - 23H1_WXE, V23.03.131.s001            
#)libhdldb.so - 23H1_WXE, V23.03.131.s001            
#)libhdlucdb.so - 23H1_WXE, V23.03.131.s001            
#)libhdlmap.so - 23H1_WXE, V23.03.131.s001            
#)libdb.so - 23H1_WXE, V23.03.131.s001            
#)libtcl.so - 23H1_WXE, V23.03.131.s001            
#)libqfsutil.so - 23H1_WXE, V23.03.131.s001            
#)libqfs.so - 23H1_WXE, V23.03.131.s001            
#)libnativeutils.so - 23H1_WXE, V23.03.131.s001            
#)libqt.so - 23H1_WXE, V23.03.131.s001            
#)libqtutil.so - 23H1_WXE, V23.03.131.s001            
#)libsd.so - 23H1_WXE, V23.03.131.s001            
000,000 s: WARNING (legacy-52507): The file descriptors limit is 4096, which is less than recommended minimum of 16384.
* System parameters:
vm/overcommit_memory: 0
vm/overcommit_ratio: 50
vm/oom_dump_tasks: 1
vm/oom_kill_allocating_task: 0
% ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63416
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 4096
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63416
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
* CPU info:
  Number of CPUs: 4
  Name: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
  Vendor: GenuineIntel, family: 6, model: 85, stepping: 4
  CPU MHz: 2294.609, BogoMIPS: 4589.21, virtualization: full
  L1d cache: 32K, L1i cache: 32K, L2 cache: 1024K, L3 cache: 25344K
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):       15       11        4        0        0        8
Swap (GB):        7        1        6
* Load info:
  785 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
               2.78 ( 70% CPU) |   1.58 ( 39% CPU) |   1.16 ( 29% CPU)
System info: sjcvl-simonett - oomr - 8834 8644 - qtInit - 2024-11-01 12:24:30 - 2.78 70% 1.58 39% 1.16 29% - 15 11 4 8 7 1 6
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):       15       11        4        0        0        8
Swap (GB):        7        1        6
* Load info:
  785 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
               2.78 ( 70% CPU) |   1.58 ( 39% CPU) |   1.16 ( 29% CPU)
System info: sjcvl-simonett - oomr - 8834 8644 - qtExit - 2024-11-01 12:24:30 - 2.78 70% 1.58 39% 1.16 29% - 15 11 4 8 7 1 6
Peak usage info for oomr (pid 8834, ppid 8644) on sjcvl-simonett: CPU usage 0.00, Peak mem (Res 0 GB, Virt 1 GB), freePhyMem 4 GB, totalPhyMem 16 GB, freeSwap 7 GB, totalSwap 8 GB
DRM memory info: sjcvl-simonett - oomr - 8834 - 8644 - unknown unlimited
## oomr exits at 11/01/2024 12:24:30 Status: 0, PID: 8834
## oomr Elapsed time: 0:00:00, CPU time: 0:00:00.00, Memory Usage: 0.8G
## Child Proc. CPU time: 0:00:00.26
000,000 s: design Command: elapsed time 1 sec.
000,000 s: INFO (legacy-765432): ./AxisWork/xeCompile.args Path not found 
000,000 s: hdldb xcva_top
000,000 s: XEC> compile -etOnly -noDbgPrepare -seed 32717173 
000,000 s: INFO: Peak Memory Usage of the program (compile) is 1307  MB 
000,000 s: INFO (legacy-46435): Successfully generate memory rules file.
000,000 s: INFO (legacy-31228): Running core compile with ice mode

## et3compile starts at 11/01/2024 12:24:30 simonett V23.03.131.s001, HOST: sjcvl-simonett, PID: 8644, DISPLAY: none
et3compile xcva_top -seed 32717173 -mode ice
000,000 s: et3compile xcva_top -seed 32717173 -mode ice <Version> V23.03.131.s001
000,000 s: 
000,000 s: INFO (qt2dadb-1035): ***COMPILING FOR IN-CIRCUIT EMULATION MODE***
000,000 s: WARNING (qt2dadb-1064): Using user defined database configuration file `/lan/cva_rel/23h1_wxe/23.03.131.s001/tools.lnx86/etc/et3/et3compile.cfg'.
000,000 s: 	This overrides program-generated file `./dbFiles/et3compile.cfg'
000,000 s: MESSAGE (legacy-0): Executing command `xbatch xcva_top xcva_top'
000,000 s: INFO : Processing Symmetric Compile...
000,001 s: Netlist optimizer initializing...
000,001 s: Palladium Z2 configuration detected.
000,001 s: Removing simple redundancies... 31404 boxes removed
000,001 s: Removing complex redundancies... 72  boxes removed
000,001 s: Relevelizing after breaking up 148, transforming 10034 and swapping 3445 muxes...
000,001 s: Saved 10034 logic boxes through muxes optimization
000,001 s: Running CBL module...
000,002 s: ---- ET5CBL: Parameters: -O2                          ---- 
000,002 s: ---- ET5CBL: Cleaning up database                     ---- 
000,002 s: ---- ET5CBL: Partitioning database into 4 parts       ---- 
000,002 s: ---- ET5CBL: Maximum 4 threads to run concurrently    ---- 
000,002 s: ---- ET5CBL: Converting database to netlists          ---- 
000,003 s: ---- ET5CBL: Clearing database                        ---- 
000,003 s: ---- ET5CBL: Thread 1: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 2: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 0: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 3: Started                        ---- 
000,003 s: ---- ET5CBL: Thread 0: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 3: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 2: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 1: Adding name listener           ---- 
000,003 s: ---- ET5CBL: Thread 0: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 3: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 1: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 2: Checking iterator consistency  ---- 
000,003 s: ---- ET5CBL: Thread 3: Expanding LUTs into ANDs       ---- 
000,003 s: ---- ET5CBL: Thread 0: Expanding LUTs into ANDs       ---- 
000,003 s: ---- ET5CBL: Thread 2: Expanding LUTs into ANDs       ---- 
000,003 s: ---- ET5CBL: Thread 1: Expanding LUTs into ANDs       ---- 
000,003 s: ---- ET5CBL: Thread 3: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 3: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 0: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 0: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 1: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 2: Removing redundant logic       ---- 
000,004 s: ---- ET5CBL: Thread 2: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 1: Rewriting DAG-aware netlist    ---- 
000,004 s: ---- ET5CBL: Thread 3: Technology mapping             ---- 
000,004 s: ---- ET5CBL: Thread 0: Technology mapping             ---- 
000,005 s: ---- ET5CBL: Thread 3: Eliminating forcible gates     ---- 
000,005 s: ---- ET5CBL: Thread 0: Eliminating forcible gates     ---- 
000,005 s: ---- ET5CBL: Thread 0: Recreating final database      ---- 
000,005 s: ---- ET5CBL: Thread 0: Disposing netlist              ---- 
000,005 s: ---- ET5CBL: Thread 1: Technology mapping             ---- 
000,005 s: ---- ET5CBL: Thread 2: Technology mapping             ---- 
000,005 s: ---- ET5CBL: Thread 1: Eliminating forcible gates     ---- 
000,005 s: ---- ET5CBL: Thread 1: Recreating final database      ---- 
000,006 s: ---- ET5CBL: Thread 1: Disposing netlist              ---- 
000,006 s: ---- ET5CBL: Thread 2: Eliminating forcible gates     ---- 
000,006 s: ---- ET5CBL: Thread 2: Recreating final database      ---- 
000,006 s: ---- ET5CBL: Thread 3: Recreating final database      ---- 
000,006 s: ---- ET5CBL: Thread 2: Disposing netlist              ---- 
000,006 s: ---- ET5CBL: Thread 3: Disposing netlist              ---- 
000,006 s: ---- ET5CBL: Joined 4 optimization threads            ---- 
000,006 s: ---- ET5CBL: Merging DADB database                    ---- 
000,006 s: ---- ET5CBL: CBL Done                                 ---- 
000,006 s: Propagation round 1...
000,006 s: Propagating and accelerating 290778 primitives
000,006 s: ...
000,006 s: Propagation round 2...
000,006 s: Propagating and accelerating 286890 primitives
000,006 s: ...
000,007 s: Cleaning up...
000,007 s: Retiming...
000,007 s: Checking for redundant memory ports...
000,007 s: 0 ports removed
000,007 s: Removing complex redundancies... 1  boxes removed
000,007 s: Checking force nets ...
000,007 s: 0 buffer inserted
000,007 s: INFO (db2util-1071): Netlist optimization gives 36 % reduction.
000,007 s:  (414304 - 150474 = 263830)
000,007 s: INFO (db2util-1119): Available configuration: 8 domains
000,007 s: INFO (db2util-1113): The design contains 263830 ET primitives (boxes).
000,007 s: EDRAMS_PER_CHIP=64
000,007 s: ACTIVE_EDRAMS_PER_P512=8
000,007 s: Palladium Z2 configuration detected...
000,007 s: file_to_tvect: xc_work/mem_placement.constraints
000,007 s: Reading file 'xcva_top.mempreset'...
000,007 s: 
000,007 s: Collecting memory ports and instances...
000,007 s: 
000,007 s: Found 250 memory ports.
000,007 s: 
000,007 s: Found 88 memory instances.
000,007 s: WARNING (db2util-1059): Design contains 27 'DO_NOT_TOUCH' memory instances
000,007 s: 
000,007 s: Instruction usage: 1.2%
000,007 s: Finding mergeable memory (step 1)...
000,007 s: .
000,007 s: 
000,007 s: Finding mergeable memory (step 2)...
000,007 s: 
000,007 s: In total, 2 memory instances are candidates for at least 1 merger
000,007 s: 
000,007 s: 
000,007 s: In total, 2 memory instances were merged into 1 merger.
000,007 s: 
000,007 s: ....
000,007 s: Evaluated for compaction 87 memory instances.
000,007 s: Targeted 81 memory instances to INTRAM, 12 to S-INTRAM, 0 to XTENSA INTRAM (X-INT), 0 to DDR4, 0 to LPDDR4.
000,007 s: Instruction usage after memory transformation: 1.2 %
000,007 s: INFO (db2util-1115): Compilation seed is 32717173
000,007 s: 
000,007 s:     Systems:     1 .
000,007 s:       Racks:     1 .
000,007 s: BrdClusters:     1 .
000,007 s:      Boards:     1 .
000,011 s:       Asics:     8 ........
000,011 s:       P512s:    64 .................................................. -     50
000,011 s:                    ..............
000,011 s:        P64s:   512 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -    500
000,012 s:                    x
000,012 s: Reducing hop at epc level.
000,012 s: CPR round  1, maxlvl 429, path head 243589 lvl 410, tail  46867, len  73, m_is_marked   0, moved 49, NC 0 
000,012 s: CPR round  2, maxlvl 357, path head 243589 lvl 357, tail 187408, len  51, m_is_marked   0, moved 22, NC 0 
000,012 s: CPR round  3, maxlvl 321, path head 243589 lvl 321, tail 209401, len  58, m_is_marked   0, moved 18, NC 0 
000,012 s: CPR round  4, maxlvl 306, path head 243589 lvl 306, tail 268854, len  49, m_is_marked   0, moved 23, NC 0 
000,012 s: CPR round  5, maxlvl 304, path head 243589 lvl 304, tail 187391, len  50, m_is_marked   0, moved 20, NC 0 
000,013 s: CPR round  6, maxlvl 297, path head 243589 lvl 297, tail 187408, len  40, m_is_marked   0, moved 15, NC 0 
000,013 s: CPR round  7, maxlvl 296, path head 243589 lvl 296, tail 268876, len  46, m_is_marked   0, moved 13, NC 0 
000,013 s: CPR round  8, maxlvl 288, path head 243589 lvl 286, tail  46867, len  47, m_is_marked   0, moved  6, NC 0 
000,013 s: CPR round  9, maxlvl 286, path head 243589 lvl 286, tail 207205, len  56, m_is_marked   0, moved 16, NC 0 
000,013 s: CPR round 10, maxlvl 277, path head 243589 lvl 277, tail 143512, len  45, m_is_marked   0, moved 14, NC 0 
000,013 s: CPR round 11, maxlvl 277, path head 243589 lvl 277, tail 187396, len  49, m_is_marked   0, moved 15, NC 1 
000,013 s: CPR round 12, maxlvl 271, path head 243589 lvl 271, tail 209034, len  58, m_is_marked   0, moved 12, NC 0 
000,013 s: CPR round 13, maxlvl 270, path head 243589 lvl 270, tail 181038, len  47, m_is_marked   0, moved  9, NC 0 
000,013 s: CPR round 14, maxlvl 266, path head 243589 lvl 266, tail 245223, len  45, m_is_marked   0, moved 11, NC 0 
000,013 s: CPR round 15, maxlvl 264, path head 243589 lvl 264, tail 209401, len  55, m_is_marked   0, moved  6, NC 0 
000,013 s: CPR round 16, maxlvl 263, path head 243589 lvl 263, tail 181223, len  59, m_is_marked   0, moved 12, NC 0 
000,013 s: CPR round 17, maxlvl 264, path head 289327 lvl 263, tail 265107, len  55, m_is_marked  23, moved  9, NC 0 
000,013 s: CPR round 18, maxlvl 262, path head 243589 lvl 262, tail 207205, len  71, m_is_marked   0, moved 18, NC 0 
000,013 s: CPR round 19, maxlvl 262, path head 243589 lvl 262, tail  59935, len  38, m_is_marked   0, moved  8, NC 1 
000,013 s: CPR round 20, maxlvl 261, path head 243589 lvl 261, tail 216609, len  78, m_is_marked  18, moved 31, NC 0 
000,013 s: CPR round 21, maxlvl 273, path head 289327 lvl 269, tail 209401, len  49, m_is_marked  32, moved  6, NC 0 
000,013 s: CPR round 22, maxlvl 260, path head 243589 lvl 260, tail 259024, len  44, m_is_marked   0, moved  4, NC 0 
000,013 s: CPR round 23, maxlvl 259, path head 243589 lvl 259, tail 209401, len  51, m_is_marked  30, moved  5, NC 0 
000,013 s: CPR round 24, maxlvl 259, path head 243589 lvl 259, tail 209401, len  54, m_is_marked  30, moved  5, NC 1 
000,013 s: CPR round 25, maxlvl 259, path head 243589 lvl 259, tail 209401, len  53, m_is_marked  30, moved  5, NC 2 
000,013 s: CPR round 26, maxlvl 259, path head 243589 lvl 259, tail 209401, len  54, m_is_marked  30, moved  5, NC 3 
000,013 s: CPR round 27, maxlvl 261, path head 289386 lvl 260, tail 209400, len  53, m_is_marked  42, moved  5, NC 0 
000,013 s: CPR round 28, maxlvl 259, path head 289327 lvl 258, tail 209400, len  54, m_is_marked  38, moved  7, NC 0 
000,013 s: CPR round 29, maxlvl 258, path head 243589 lvl 258, tail 209465, len  52, m_is_marked  34, moved  7, NC 0 
000,013 s: CPR round 30, maxlvl 269, path head 289327 lvl 268, tail 209464, len  53, m_is_marked  40, moved  6, NC 0 
000,013 s: CPR round 31, maxlvl 258, path head 289327 lvl 257, tail 209464, len  53, m_is_marked  38, moved  3, NC 0 
000,013 s: CPR round 32, maxlvl 257, path head 243589 lvl 257, tail 209464, len  54, m_is_marked  36, moved  5, NC 0 
000,013 s: CPR round 33, maxlvl 258, path head 289327 lvl 257, tail 209462, len  54, m_is_marked  42, moved  3, NC 0 
000,013 s: CPR round 34, maxlvl 257, path head 240408 lvl 222, tail 209462, len  69, m_is_marked  33, moved 22, NC 0 
000,013 s: CPR round 35, maxlvl 256, path head 243589 lvl 256, tail 209462, len  54, m_is_marked  36, moved  4, NC 0 
000,013 s: CPR round 36, maxlvl 256, path head 243589 lvl 256, tail 209462, len  54, m_is_marked  36, moved  4, NC 1 
000,013 s: CPR round 37, maxlvl 256, path head 243589 lvl 256, tail 209462, len  54, m_is_marked  38, moved  2, NC 2 
000,013 s: CPR round 38, maxlvl 256, path head 243589 lvl 256, tail 209462, len  54, m_is_marked  45, moved  4, NC 3 
000,013 s: CPR round 39, maxlvl 256, path head 243589 lvl 256, tail 209462, len  55, m_is_marked  39, moved  3, NC 4 
000,013 s: CPR round 40, maxlvl 255, path head 243589 lvl 255, tail 209462, len  54, m_is_marked  41, moved  3, NC 0 
000,013 s: CPR round 41, maxlvl 255, path head 243589 lvl 255, tail 209462, len  54, m_is_marked  39, moved  3, NC 1 
000,013 s: CPR round 42, maxlvl 255, path head 243589 lvl 255, tail 209462, len  53, m_is_marked  36, moved  4, NC 2 
000,013 s: CPR round 43, maxlvl 255, path head 243589 lvl 255, tail 209462, len  53, m_is_marked  36, moved  4, NC 3 
000,013 s: CPR round 44, maxlvl 255, path head 243589 lvl 255, tail 209462, len  54, m_is_marked  38, moved  4, NC 4 
000,013 s: CPR round 45, maxlvl 255, path head 243589 lvl 255, tail 209462, len  54, m_is_marked  36, moved  4, NC 5 
000,013 s: CPR round 46, maxlvl 260, path head 289386 lvl 259, tail 209456, len  50, m_is_marked  38, moved  3, NC 0 
000,013 s: CPR round 47, maxlvl 259, path head 289386 lvl 258, tail 209456, len  51, m_is_marked  44, moved  2, NC 0 
000,013 s: CPR round 48, maxlvl 257, path head 289386 lvl 255, tail 209456, len  52, m_is_marked  38, moved  4, NC 0 
000,013 s: CPR round 49, maxlvl 256, path head 289386 lvl 254, tail 209456, len  52, m_is_marked  40, moved  5, NC 0 
000,013 s: CPR round 50, maxlvl 255, path head 289386 lvl 253, tail 209456, len  53, m_is_marked  42, moved  4, NC 0 
000,013 s: CPR round 51, maxlvl 256, path head 289327 lvl 255, tail 209442, len  51, m_is_marked  40, moved  0, NC 0 
000,013 s: CPR round 52, maxlvl 256, path head 289155 lvl 255, tail 209441, len  51, m_is_marked  47, moved  0, NC 1 
000,013 s: CPR round 53, maxlvl 256, path head 288634 lvl 247, tail 154925, len  43, m_is_marked   0, moved 23, NC 1 
000,013 s: CPR round 54, maxlvl 256, path head 288634 lvl 243, tail 209440, len  49, m_is_marked  41, moved  4, NC 2 
000,013 s: CPR round 55, maxlvl 256, path head 288121 lvl 243, tail 209439, len  44, m_is_marked  27, moved 10, NC 3 
000,013 s: CPR round 56, maxlvl 256, path head 286888 lvl 242, tail 209438, len  50, m_is_marked  39, moved  1, NC 4 
000,013 s: CPR round 57, maxlvl 256, path head    114 lvl 242, tail 209434, len  51, m_is_marked  41, moved  3, NC 5 
000,013 s: CPR round 58, maxlvl 256, path head 287408 lvl 233, tail 209465, len  52, m_is_marked  42, moved  4, NC 6 
000,013 s: CPR round 59, maxlvl 256, path head  94458 lvl 197, tail 201464, len  37, m_is_marked   0, moved 16, NC 7 
000,013 s: CPR round 60, maxlvl 256, path head 242740 lvl 230, tail 209465, len  51, m_is_marked  50, moved  1, NC 8 
000,013 s: CPR round 61, maxlvl 256, path head 240898 lvl 223, tail  47829, len  86, m_is_marked   0, moved 32, NC 9 
000,013 s: Total relocated = 407
000,013 s: Maximum number of hops in all paths = 255
## et3compile exits at 11/01/2024 12:24:43 Status: 0, PID: 8644
## et3compile Elapsed time: 0:00:13, CPU time: 0:00:28.21, Memory Usage: 2.8G
000,013 s: 0 32717173 -1 0 0
000,013 s: ^D
* Memory info:
              total     used     free   shared  buffers   cached
Mem  (GB):       15       11        3        0        0        8
Swap (GB):        7        1        6
* Load info:
  778 threads
  Load (avg):    1 min (% CPU) |     5 min (% CPU) |    15 min (% CPU)
               2.69 ( 67% CPU) |   1.62 ( 40% CPU) |   1.18 ( 30% CPU)
System info: sjcvl-simonett - xeCompile - 8644 8642 - qtExit - 2024-11-01 12:24:43 - 2.69 67% 1.62 40% 1.18 30% - 15 11 3 8 7 1 6
Peak usage info for xeCompile (pid 8644, ppid 8642) on sjcvl-simonett: CPU usage 0.00, Peak mem (Res 1 GB, Virt 3 GB), freePhyMem 4 GB, totalPhyMem 16 GB, freeSwap 7 GB, totalSwap 8 GB
DRM memory info: sjcvl-simonett - xeCompile - 8644 - 8642 - unknown unlimited
## xeCompile exits at 11/01/2024 12:24:43 Status: 0, PID: 8644
## xeCompile Elapsed time: 0:00:14, CPU time: 0:00:28.35, Memory Usage: 2.8G
## Child Proc. CPU time: 0:00:00.73
